"""Add many-to-many relationship between Plant and Product

Revision ID: 0afc9c7bb9ec
Revises: b1848ca11cf2
Create Date: 2025-11-06 09:36:29.142520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afc9c7bb9ec'
down_revision = 'b1848ca11cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_product_association',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_product_association')
    # ### end Alembic commands ###
