"""Add plant_id foreign keys and migrate data

Revision ID: 4cf741fa41f1
Revises: ae472c539922
Create Date: 2025-11-06 07:07:39.795348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf741fa41f1'
down_revision = 'ae472c539922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True))
        batch_op.alter_column('plant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key('fk_quality_report_plant', 'plant', ['plant_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True))
        batch_op.alter_column('plant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key('fk_user_plant', 'plant', ['plant_id'], ['id'])
    # ### end Alembic commands ###

    # --- ADD THE FOLLOWING CODE BLOCK ---
    op.execute("""
        UPDATE quality_report
        SET plant_id = (
            SELECT id FROM plant
            WHERE plant.name = quality_report.plant_name
        )
    """)
    
    op.execute("""
        UPDATE "user"
        SET plant_id = (
            SELECT id FROM plant
            WHERE plant.name = "user".plant_name
        )
    """)
    # --- END OF ADDED CODE ---

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('plant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('plant_id')

    with op.batch_alter_table('quality_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('plant_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###
