"""Add analytics_event table

Revision ID: 96bffa91bba0
Revises: 0afc9c7bb9ec
Create Date: 2025-11-06 11:23:58.781892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bffa91bba0'
down_revision = '0afc9c7bb9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.create_index('idx_event_timestamp', ['event_type', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_event_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_event_event_type'))
        batch_op.drop_index('idx_event_timestamp')

    op.drop_table('analytics_event')
    # ### end Alembic commands ###
