"""Add code column to Plant table with named constraint

Revision ID: ae472c539922
Revises: c898f5a75840
Create Date: 2025-11-06 07:02:25.471698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae472c539922'
down_revision = 'c898f5a75840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_plant_code', ['code'])
        batch_op.create_unique_constraint('uq_plant_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_constraint('uq_plant_name', type_='unique')
        batch_op.drop_constraint('uq_plant_code', type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
