"""Add machine_codes to QualityReport

Revision ID: c898f5a75840
Revises: 98f298c4b6b4
Create Date: 2025-09-03 14:12:55.612126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c898f5a75840'
down_revision = '98f298c4b6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_codes', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_report', schema=None) as batch_op:
        batch_op.drop_column('machine_codes')

    # ### end Alembic commands ###
