"""Add index to quality_report batch_code

Revision ID: dc6e5278cc68
Revises: 4cf741fa41f1
Create Date: 2025-11-06 07:28:18.230221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6e5278cc68'
down_revision = '4cf741fa41f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_report', schema=None) as batch_op:
        batch_op.create_index('idx_report_batch_code', ['batch_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_report', schema=None) as batch_op:
        batch_op.drop_index('idx_report_batch_code')

    # ### end Alembic commands ###
